fix cask installation and add failure reporting to brew/cask install

diff --git a/installers/shared_functions b/installers/shared_functions
--- a/installers/shared_functions
+++ b/installers/shared_functions
@@ -16,7 +16,12 @@ brew_install_if_missing () {
   echo -n "Installing $brew_name: "
   if [[ -z $(brew list | grep -e \^$1$) ]]; then
     brew install $brew_name
-    echo "...done"
+    SUCCESS=$?
+    if [[ SUCCESS == 0 ]]; then
+      echo "...done."
+    else
+      echo "...failed."
+    fi
   else
    echo "...already installed."
   fi
@@ -42,9 +47,14 @@ brew_cask_install_if_missing () {
   fi
 
   echo -n "Installing $cask_name: "
-  if [[ -z $(brew cask list | grep -e \^$1$) ]]; then
-    brew cask install $cask_name
-    echo "...done."
+  if [[ -z $(brew cask list | egrep -e "$cask_name($|\s)") ]]; then
+    brew cask install $cask_name > /dev/null
+    SUCCESS=$?
+    if [[ SUCCESS == 0 ]]; then
+      echo "...done."
+    else
+      echo "...failed."
+    fi
   else
    echo "...already installed."
   fi
